[globals]
# Sets global settings
load_data = True
experiment_name = gv020a
working_directory =  /raid1/scratch/kelvinw/gv020_working_dir/gv020a_working_dir
; working_directory = /raid1/scratch/kelvinw/rsg12_working_dir
uvfits_file =  /raid1/scratch/kelvinw/gv020_working_dir/uvfits_files/gv020a.UVFITS
; uvfits_file = 
use_singularity = False
aoflagger_path = /raid1/scratch/kelvinw/singularity_containers/lofar_aoflagger_3.1.0.sif
wsclean_sif= /raid1/scratch/kelvinw/singularity_containers/wsclean_working.simg
singularity_container = /home/kelvin/Desktop/singularity/casa6_wsclean2_aoflagger3.sif

[casa]
use_casa = False
attach_metadata = False
idifitsfiles = /raid1/scratch/kelvinw/gv020_fitsfiles/gv020b_copy_fitsfiles
antab_file = /raid1/scratch/kelvinw/gv020_fitsfiles/gv020b_copy_fitsfiles/gv020b_1.antab
uvflg_file = /raid1/scratch/kelvinw/gv020_fitsfiles/gv020b_copy_fitsfiles/gv020b_1.uvflg

; idifitsfiles = /raid1/scratch/kelvinw/rsg12_1
; antab_file = /raid1/scratch/kelvinw/rsg12_1/rsg12_1.antab
; uvflg_file = /raid1/scratch/kelvinw/rsg12_1/rsg12_1.uvflg
do_apriori_cal = False
apply_apriori_cal = False

[basic]
target = M15PSRC
phase_calibrator = J2139+1423
fringe_finder = 3C454.3
integration_time = 0.5

; target = J1926+4441
; phase_calibrator = J1926+4441
; fringe_finder = J1926+4441
; integration_time = 2

do_split =  True
timebin = 2s
width = 4
verbosity = True

[flagging]
do_flagging = False
use_aoflagger = False
flagging_strategy = /raid1/scratch/kelvinw/casa_vlbi/data/flagging/generic_strategy.lua
; flagging_strategy = /raid1/scratch/kelvinw/casa_vlbi/data/flagging/faint_sources.rfis
manual_file = /raid1/scratch/kelvinw/casa_vlbi/data/flagging/gv020a.flag
; manual_file = 
edge_channel_fraction = 0.01
flag_antenna = False
antenna_to_flag = 

[calibrate]
do_sbd_fringe = True
apply_sbd = True
refant = EF,JB,WB,MC
timerange = 18:02:00~18:03:00 
timerange_ar = 22:55:00~22:56:00
; timerange_ar = 
; timerange = 10:48:20.0~10:49:20.0 
; timerange_ar = 22:33:00~22:54:00
; timerange = 12:54:00~12:55:30
snr_sbd = 7
do_mbd_fringe =  True
apply_mbd = True
snr_mbd = 7
solint = 60
do_bpass = True
apply_bpass = True
imsize = 640,640
make_dirty_map = True

[selfcal]
do_selfcal = False
use_tclean = False
use_wsclean = True
pybdsf_threshold = 4
pybdsf_niter = 1
nloops = 2
; nloops = 1
calmode = p,ap
; calmode = p
gaintype= T,T
; gaintype = T
solint_selfcal = 90s,300s
; solint_selfcal = inf
threshold = 18,9
tclean_threshold = 30mJy

; threshold = 10
minsnr = 3,3
; minsnr = 3
cell = 1.3mas
niter = 100000
niter_final = 100000
threshold_final = 3

robust = 0.5

spw = 17 
abs_mem = 4 
weighting=briggs
detection_threshold = 5.0
apply_to_target = False
detect_sources = False


[pbcor]
do_pbcor = False
pb_file = /raid1/scratch/kelvinw/casa_vlbi/data/primary_beams/pb.json


