[globals]
# Sets global settings
load_data = True
experiment_name = tl016b
working_directory =  /home/kelvin/Desktop/TL016B/working_directory

uvfits_file = 
use_singularity = False
aoflagger_path = 
wsclean_sif= 
singularity_container = 

[apriori]
use_casa = True
attach_metadata = False
fitsfiles_dir = /home/kelvin/Desktop/TL016B/
antab_file = /home/kelvin/Desktop/TL016B/working_directory/tl016b.antab
uvflg_file = 
do_apriori_cal = False
apply_apriori_cal = False

[basic]

target =  4C39.25
phase_calibrator = J1154+6022
fringe_finder = J1203+6031
integration_time = 2

do_split =  False
timebin = 2
width = 8
verbosity = False

[flagging]
do_flagging =   True
use_aoflagger = False
flagging_strategy = 
manual_file = 

edge_channel_fraction = 0.02
flag_antenna = False
antenna_to_flag = AR
export_uvfits = False

; [calibrate]
; do_tec_corrections = False
; do_sbd_fringe = False
; apply_sbd = False
; refant = EF,JB,WB
; timerange = 18:02:00~18:03:00 

; snr_sbd = 7
; do_mbd_fringe =  False
; apply_mbd = False
; snr_mbd = 7
; solint = 60
; do_bpass = False
; apply_bpass = False
; imsize = 640,640
; make_dirty_map = False
; split_calibrated = False

; [selfcal]
; do_selfcal = False
; use_tclean = False
; use_wsclean = False
; pybdsf_threshold = 5
; pybdsf_niter = 1
; nloops = 2
; ; nloops = 1
; calmode = p,ap
; ; calmode = p
; gaintype= G,G
; ; gaintype = T
; solint_selfcal = 90s,90s
; threshold = 7,5
; tclean_threshold = 30mJy
; minsnr = 3,3
; cell = 1mas
; niter = 100000
; niter_final = 100000
; threshold_final = 3

; robust = 0.5

; spw = 17 
; abs_mem = 4 
; weighting=briggs
; detection_threshold = 5.0
; apply_to_target = False
; detect_sources = False


; [pbcor]
; do_pbcor = False
; pb_file = 


