[globals]
# Sets global settings
load_data = True
experiment_name = tl016
working_directory = /mirror2/scratch/kelvinw/TL016B/working_directory
telescope = VLBA
uvfits_file = 
use_singularity = False
aoflagger_path = 
wsclean_sif = /mirror2/scratch/kelvinw/singularity_containers/wsclean_working.simg
singularity_container = 

[apriori]
use_casa = True
attach_metadata = False
fitsfiles_dir = /mirror2/scratch/kelvinw/TL016B
antab_file = 
uvflg_file = 
do_apriori_cal = True
apply_apriori_cal = True

[basic]

target =  J1203+6031
phase_calibrator = J1154+6022
fringe_finder =  4C39.25
integration_time = 2

do_split =  False
timebin = 2
width = 8
verbosity = False

[flagging]
do_flagging =   True
use_aoflagger = False
flagging_strategy = 
manual_file = 

edge_channel_fraction = 0.02
flag_antenna = False
antenna_to_flag = 
export_uvfits = False

[calibrate]
do_tec_corrections = True
do_sbd_fringe = True
apply_sbd = True
refant = FD,PT
timerange = 

snr_sbd = 7
do_mbd_fringe =  True
apply_mbd = True
snr_mbd = 7
solint = 30
do_bpass = True
apply_bpass = True
make_dirty_map = True
use_tclean = False
use_wsclean = True

[selfcal]
; do_selfcal = False

; pybdsf_threshold = 5
; pybdsf_niter = 1
; nloops = 2
; ; nloops = 1
; calmode = p,ap
; ; calmode = p
; gaintype= G,G
; ; gaintype = T
; solint_selfcal = 90s,90s
; threshold = 7,5
; tclean_threshold = 30mJy
; minsnr = 3,3
; cell = 1mas
; niter = 100000
; niter_final = 100000
; threshold_final = 3

; robust = 0.5

; spw = 17 
; abs_mem = 4 
; weighting=briggs
; detection_threshold = 5.0
; apply_to_target = False
; detect_sources = False


; [pbcor]
; do_pbcor = False
; pb_file = 


