[globals]
# Sets global settings
set_user = 5
experiment_name = gv020b
working_directory =  /raid1/scratch/kelvinw/gv020_working_dir/uvfits_files
start_tv = False
indisk = 1 
inseq = 1
inclass = UVDATA


[load_data]
zap_data = False
load_data = True
fitsfiles_directory = /raid1/scratch/kelvinw/gv020_fitsfiles/gv020b_fitsfiles
file_extension_for_flagging = IDI
file_extension_for_cal = FITS
tasav_file = gv020b_1.tasav.FITS
; tasav_file = gv020a.tasav.FITS
pointing = 1
integration_time = 0.5

[sources]
phase_calibrator = J2139+1423
target = M15PSRC
fringe_finder = 3C454.3

[flagging]
do_flagging = True
aoflagger_sif = /raid1/scratch/kelvinw/singularity_containers/lofar_aoflagger_3.1.0.sif
flagging_strategy = /raid1/scratch/kelvinw/casa_vlbi/data/flagging/generic_strategy.lua

[calibrate]
refant = EF
searchants = JB,WB,MC
do_amp_parang_correction = False
do_tec_correction = False
do_singleband_fring = False
fring_timerange = 0,19,38,0,0,19,39,0
apply_singleband_corrections = False
do_global_fring = False
fring_solint = 1
fring_snr = 7
apply_global_fring_corrections = False
do_bandpass = False
apply_bpass_corrections = False

apply_all_calibrations = False

[split]
do_splat = False
write_fits = False

