[globals]
# Sets global settings
set_user = 5
experiment_name = gv020a
working_directory = /raid1/scratch/kelvinw/gv020_working_dir/gv020a
start_tv = False
indisk = 1 
inseq = 1
inclass = UVDATA


[load_data]
zap_data = False
load_data = False
fitsfiles_directory = /raid1/scratch/kelvinw/gv020_fitsfiles/gv020a_fitsfiles/
; fitsfiles_directory = /raid1/scratch/kelvinw/n14c3_fitsfiles
idifitsfiles = IDI
file_extension_for_flagging = FITS
file_extension_for_cal = FITS
; tasav_file = gv020b_1.tasav.FITS
tasav_file = gv020a.tasav.FITS
; tasav_file = n14c3.tasav.FITS
pointing = 1
integration_time = 0.25

[sources]
phase_calibrator = J2139+1423
target = M15
fringe_finder = 3C454.3

; phase_calibrator = 1848+283
; target = J1849+3024
; fringe_finder = 1848+283


[flagging]
do_flagging = False
use_aoflagger = False
aoflagger_sif = /raid1/scratch/kelvinw/singularity_containers/lofar_aoflagger_3.1.0.sif
flagging_strategy = /raid1/scratch/kelvinw/casa_vlbi/data/flagging/generic_strategy.lua
manual_file = /raid1/scratch/kelvinw/casa_vlbi/data/flagging/gv020a_final.flag
; manual_file = 

[calibrate]
refant = EF
searchants = EF,JB,WB,MC
; searchants = JB,WB
do_amp_parang_correction = False
do_tec_correction = False
do_singleband_fring = True
fring_timerange = 
fring_timerange_ar_down = 0,19,48,30,0,19,49,30
fring_timerange_ar_up = 0,22,43,30,0,22,44,0
; fring_timerange = 0,18,2,0,0,18,3,0 
; fring_timerange = 0,10,48,20,0,10,49,20,0
; fring_timerange = 0,14,58,30,0,14,59,30
; fring_timerange = 0,13,53,20,0,13,54,20
; fring_timerange = 0,14,48,0,14,49,0 # epoch e
; fring_timerange = 0,13,28,23,0,13,29,19
apply_singleband_corrections = True
do_global_fring = False
fring_solint = 1
fring_snr = 7
apply_global_fring_corrections = False
do_bandpass = False
apply_bpass_corrections = False

[split]
do_splat = False
write_fits = False

[selfcal]
split_selfcal = False
make_dirty_map = False
do_selfcal = False
use_tclean = False
use_wsclean = True
wsclean_sif = /raid1/scratch/kelvinw/singularity_containers/wsclean_working.simg
; wsclean_sif = /home/kelvin/Desktop/singularity/wsclean-v3.3-no-cuda.sif 
pybdsf_threshold = 4
pybdsf_niter = 1
cell = 1mas
imsize = 640,640
nloops = 2
; nloops = 1
calmode = p,ap
; calmode = p
gaintype= T,T
; gaintype = T
solint_selfcal = 90s,300s
; solint_selfcal = inf
threshold = 9,7
tclean_threshold = 30mJy

; threshold = 10
minsnr = 3,3
; minsnr = 3
niter = 100000
niter_final = 100000
threshold_final = 3

robust = 0.5

spw = 17 
abs_mem = 4 
weighting=briggs
detection_threshold = 4.0
apply_to_target = False
detect_sources = False


